export default function SectionHeader({ eyebrow, title, blurb }) {
  return (
    <div>
      {eyebrow && <p className="text-xs font-semibold uppercase tracking-wide text-marigold-600 mb-1">{eyebrow}</p>}
      <h1 className="font-display text-2xl font-semibold text-ink">{title}</h1>
      {blurb && <p className="text-sm text-ink-soft/60 mt-1 max-w-2xl">{blurb}</p>}
    </div>
  );
}

export function NoteTag({ children = "Illustrative data, generated for evaluation purposes" }) {
  return (
    <p className="text-[11px] text-ink-soft/40 mt-2 inline-flex items-center gap-1">
      <span className="h-1.5 w-1.5 rounded-full bg-marigold-400" /> {children}
    </p>
  );
}

export function AiDisclaimer({ children }) {
  return (
    <p className="text-[11px] text-ink-soft/45 rounded-lg bg-sand-100 px-3 py-2 leading-relaxed">
      {children || "Scores and classifications are computed deterministically; written text is generated by Hugging Face's free-tier hosted Inference API — not a substitute for professional advice."}
    </p>
  );
}
