import { useState, useEffect } from "react";
import { CURRENT_COOP } from "../../data/seed";
import { demandRadarForCoop, demandRecommendation, demandRecommendationAI } from "../../lib/logic";
import { CompareBarChart } from "../../components/shared/ChartPair";
import InsightCard from "../../components/shared/InsightCard";
import SectionHeader, { AiDisclaimer } from "../../components/shared/SectionHeader";
import { MapPin, CalendarDays, TrendingUp, TrendingDown, Minus } from "lucide-react";

const TREND_ICON = { rising: TrendingUp, falling: TrendingDown, steady: Minus };

const STATE_STYLES = {
  healthy: "border-coop-500/30 bg-coop-500/10 text-coop-600",
  shortage: "border-marigold-400/40 bg-marigold-100 text-marigold-700",
  critical: "border-alert-500/40 bg-alert-50 text-alert-600",
};

// Shortage/critical state is always deterministic (computed in demandRadarForCoop);
// only this written sentence is model-generated. Shows the template instantly, then
// swaps in the real local-model sentence once it resolves.
function RecommendationText({ row }) {
  const [text, setText] = useState(() => demandRecommendation(row));

  useEffect(() => {
    let cancelled = false;
    demandRecommendationAI(row)
      .then((aiText) => {
        if (!cancelled && aiText) setText(aiText);
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [row.service.id]);

  return <>{text}</>;
}

export default function DemandRadar() {
  const rows = demandRadarForCoop(CURRENT_COOP.id);
  const chartData = rows.map((r) => ({ name: r.service.name, Historical: r.historical, Predicted: r.predicted }));

  return (
    <div className="space-y-8">
      <SectionHeader
        eyebrow="AI Demand Radar"
        title="Where demand is heading next"
        blurb="Predicted vs historical booking volume per service — where it's concentrated, which day it peaks, and which way it's trending — computed from real booking, locality, and worker-supply data in the cooperative."
      />
      <AiDisclaimer>Shortage/critical status, top locality, peak day, and trend direction are all computed deterministically from historical bookings and current worker supply — only the written recommendation below is generated by Hugging Face's free-tier hosted AI.</AiDisclaimer>

      <div className="rounded-xl2 border border-teal-100 bg-white p-4 md:p-5 shadow-card">
        <p className="text-sm font-medium text-ink-soft/70 mb-2">Historical vs predicted bookings, by service</p>
        <CompareBarChart
          data={chartData}
          xKey="name"
          bars={[
            { key: "Historical", name: "Historical (45d)", color: "#2A7D6E" },
            { key: "Predicted", name: "Predicted (next 30d)", color: "#D9A441" },
          ]}
        />
      </div>

      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {rows.map((r) => {
          const TrendIcon = TREND_ICON[r.trend] || Minus;
          return (
            <div key={r.service.id} className="rounded-xl2 border border-teal-100 bg-white p-4 shadow-card">
              <div className="flex items-center justify-between">
                <p className="font-medium text-ink">{r.service.name}</p>
                <span className={`text-[11px] font-semibold px-2 py-0.5 rounded-full border capitalize ${STATE_STYLES[r.state]}`}>{r.state}</span>
              </div>
              <p className="text-xs text-ink-soft/60 mt-2">
                {r.workerCount} worker(s) · {r.demandPerWorker} bookings/worker
              </p>
              <div className="mt-2 pt-2 border-t border-sand-100 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-ink-soft/55">
                {r.topLocality && (
                  <span className="inline-flex items-center gap-1"><MapPin size={11} /> {r.topLocality}</span>
                )}
                {r.peakDay && (
                  <span className="inline-flex items-center gap-1"><CalendarDays size={11} /> Peaks {r.peakDay}</span>
                )}
                <span className="inline-flex items-center gap-1 capitalize">
                  <TrendIcon size={11} /> {r.trend}
                </span>
              </div>
            </div>
          );
        })}
      </div>

      <div>
        <p className="font-display text-lg font-semibold text-ink mb-3">Recommendations</p>
        <div className="grid sm:grid-cols-2 gap-3">
          {rows
            .filter((r) => r.state !== "healthy")
            .map((r) => (
              <InsightCard
                key={r.service.id}
                tone={r.state === "critical" ? "alert" : "marigold"}
                insight={`${r.service.name} needs attention`}
                reason={<RecommendationText row={r} />}
                action={r.state === "critical" ? "Open onboarding drive" : "Review cross-training options"}
              />
            ))}
          {rows.every((r) => r.state === "healthy") && (
            <InsightCard tone="teal" insight="Supply is matching demand across all services" reason="No service is currently in shortage or critical state." action="No action needed this cycle." />
          )}
        </div>
      </div>
    </div>
  );
}
