import { useState, useEffect } from "react";
import { ArrowDown, ArrowUp, Network } from "lucide-react";
import { COOPERATIVES } from "../../data/seed";
import { federationInsights, federationInsightsAI, cooperativeNetworkMatches } from "../../lib/logic";
import InsightCard from "../../components/shared/InsightCard";
import SectionHeader, { AiDisclaimer, NoteTag } from "../../components/shared/SectionHeader";

function NetworkMatchCard({ match }) {
  return (
    <div className="rounded-xl2 border border-teal-100 bg-white p-4 shadow-card">
      <p className="text-xs font-semibold uppercase tracking-wide text-ink-soft/45 mb-3">{match.service.name}</p>
      <div className="flex items-center justify-between gap-2">
        <div className="min-w-0 flex-1">
          <p className="text-[11px] text-coop-600 font-semibold uppercase tracking-wide">Surplus</p>
          <p className="text-sm font-medium text-ink truncate">{match.from.name}</p>
          <p className="text-[11px] text-ink-soft/55">{match.fromIdleCapacity} idle slot(s)/week</p>
        </div>
        <div className="shrink-0 flex flex-col items-center px-2">
          <ArrowUp size={13} className="text-ink-soft/30" />
          <p className="text-[9px] font-semibold text-ink-soft/45 tracking-wide leading-tight text-center my-0.5">
            SAHAAY
            <br />
            NETWORK
          </p>
          <ArrowDown size={13} className="text-ink-soft/30" />
        </div>
        <div className="min-w-0 flex-1 text-right">
          <p className={`text-[11px] font-semibold uppercase tracking-wide ${match.toState === "critical" ? "text-alert-600" : "text-marigold-600"}`}>
            {match.toState}
          </p>
          <p className="text-sm font-medium text-ink truncate">{match.to.name}</p>
          <p className="text-[11px] text-ink-soft/55">{match.toDemandPerWorker} bookings/worker</p>
        </div>
      </div>
      <div className="mt-3 pt-3 border-t border-sand-100">
        <p className="text-xs text-ink-soft/65">
          Route <strong className="text-ink">~{match.suggestedSlots} booking(s)/week</strong> of {match.service.name.toLowerCase()} work
          from {match.from.name} to {match.to.name}.
        </p>
      </div>
    </div>
  );
}

export default function FederationInsights() {
  // Which cooperative is under/over network average is always deterministic
  // (computed in federationInsights/federationInsightsAI). Show the template
  // version instantly, then swap in the real local-model-written text once it
  // resolves — avoids a blank state while the model loads.
  const [insights, setInsights] = useState(() => federationInsights(COOPERATIVES));
  const networkMatches = cooperativeNetworkMatches(COOPERATIVES).slice(0, 6);

  useEffect(() => {
    let cancelled = false;
    federationInsightsAI(COOPERATIVES)
      .then((written) => {
        if (!cancelled && written?.length) setInsights(written);
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="space-y-8">
      <SectionHeader
        eyebrow="Federation Insights"
        title="Network-wide recommendations"
        blurb="Computed by comparing each cooperative's live metrics against the network average — not hardcoded copy."
      />
      <AiDisclaimer>Which cooperative is under/over network average is computed deterministically — only the written insight/reason/action text is generated by Hugging Face's free-tier hosted AI.</AiDisclaimer>
      <div className="grid sm:grid-cols-2 gap-3">
        {insights.map((ins, i) => (
          <InsightCard key={i} tone={ins.tone || (i === 0 ? "alert" : i === 1 ? "marigold" : "teal")} insight={ins.insight} reason={ins.reason} action={ins.action} />
        ))}
      </div>

      <div>
        <div className="flex items-center gap-2 mb-1">
          <Network size={18} className="text-teal-600" />
          <p className="font-display text-lg font-semibold text-ink">Cooperative Network</p>
        </div>
        <p className="text-sm text-ink-soft/60 mb-3 max-w-2xl">
          One cooperative short-handed on a service, another with idle capacity for that same service — matched
          directly by service, not just by overall utilization.
        </p>
        {networkMatches.length ? (
          <div className="grid sm:grid-cols-2 gap-3">
            {networkMatches.map((m, i) => (
              <NetworkMatchCard key={`${m.service.id}-${m.from.id}-${m.to.id}-${i}`} match={m} />
            ))}
          </div>
        ) : (
          <InsightCard tone="teal" insight="No shortage/surplus pairs right now" reason="No cooperative currently has both a service in shortage and another with spare capacity for it." action="No routing needed this cycle." />
        )}
        <NoteTag>Shortage and surplus states are computed per service from live booking and capacity data — routing suggestions are illustrative, not dispatched automatically.</NoteTag>
      </div>
    </div>
  );
}
